Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DiabeticAide.Data;
using DiabeticAide.Models;
using DiabeticAide.Models.ViewModels;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;

namespace DiabeticAide.Controllers
{
    public class DataController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

  

        public DataController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: Data
        public async Task<ActionResult> Index()
        {
            var user = await GetUserAsync();




           
            


            var patientsUserIsHelperFor = await _context.UserHelpers
                .Where(uh => uh.HelperId == user.Id)
                .Include(u => u.Patient)
                .Select(use => new UserViewModel()
                {
                    UserId = use.Patient.Id,
                    FirstName = use.Patient.FirstName,
                    LastName = use.Patient.LastName
                })
                .ToListAsync();

            if (user.IsPatient == true)
            {
                var currentUserModel = new UserViewModel()
                {
                    Id = 1,
                    UserId = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName
                };
                patientsUserIsHelperFor.Insert(0,currentUserModel);
            }

            return View(patientsUserIsHelperFor);


        }

        // GET: Data/Details/5
        public async Task<ActionResult> Details(string userId)
        {
            var viewModel = new UserDataViewModel();
            var user = await GetUserAsync();

            var patient = await _context.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == userId);

            var userData = await _context.UserData.Where(p => p.UserId == userId).Include(u=> u.User).ToListAsync();

            viewModel.User = user;
            viewModel.Patient = patient;
            viewModel.UsersData = userData;
            return View(viewModel);
        }

        


        // GET: Data/Create/userId

        public ActionResult Create(string userId)
        {

            return View(userId);
        }

        // POST: Data/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(string userId, UserData data)
        {
            try
            {
                // TODO: Add insert logic here
                var user = await GetUserAsync();


                var newUserData = new UserData()
                {                   
                    Note = data.Note,
                    Reading = data.Reading,
                    DateTime = DateTime.Now

                };
                if(userId == null)
                {
                    newUserData.UserId = user.Id;
                }
                else
                {
                    newUserData.UserId = userId;
                }

                _context.UserData.Add(newUserData);
                await _context.SaveChangesAsync();
                if(userId != null)
                {
                return RedirectToAction("Details",new { userId = userId });

                }
                else
                {
                return RedirectToAction("Details", new { userId = user.Id });

                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Data/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var data = await _context.UserData.Include(u => u.User).FirstOrDefaultAsync(d => d.Id == id);
            return View(data);
        }

        // POST: Data/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UserData data)
        {
            try
            {
                // TODO: Add update logic here

                _context.UserData.Update(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { id = data.UserId, userId = data.UserId });
            }
            catch
            {
                return View();
            }
        }

        // GET: Data/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var data = await _context.UserData.Include(u=>u.User).FirstOrDefaultAsync(d => d.Id == id);
            return View(data);
        }

        // POST: Data/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, UserData data)
        {
            try
            {
                // TODO: Add delete logic here
                _context.UserData.Remove(data);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new { userId = data.UserId });
            }
            catch
            {
                return View();
            }
        }


        public async Task<ActionResult> Chart(string patientId, string chartLength)
        {
            var user = await GetUserAsync();
            var viewModel = new UserDayChartViewModel()
            {
                ReadingValues = new List<AreaSeriesData>(),
                ReadingTimes = new List<string>()
            };
            var patient = await _context.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == patientId);
            var chartData = new List<UserData>();
            if (chartLength == "Month")
            {
                var thisMonth = DateTime.Now.Month;
             chartData = await _context.UserData.Where(ud => ud.UserId == patient.Id && ud.DateTime.Month == thisMonth).ToListAsync();
                viewModel.ChartTitle = "This Month's Chart";
            }else if(chartLength == "Year")
            {
                var thisYear = DateTime.Now.Year;
                chartData = await _context.UserData.Where(ud => ud.UserId == patient.Id && ud.DateTime.Year == thisYear).ToListAsync();
                viewModel.ChartTitle = "This Year's Chart";

            }else if (chartLength == "Day")
            {
                var today = DateTime.Now.Date;
                chartData = await _context.UserData.Where(ud => ud.UserId == patient.Id && ud.DateTime.Date == today).ToListAsync();
                viewModel.ChartTitle = "Today's Chart";
            }


            

            

            foreach (var item in chartData)
            {
                var areaSeriesData = new AreaSeriesData()
                {
                    Name = item.Note,
                    Y = item.Reading
                };

                viewModel.ReadingValues.Add(areaSeriesData);
                viewModel.ReadingTimes.Add(item.DateTime.ToString());

            }


            viewModel.User = user;
            viewModel.Patient = patient;


            return View(viewModel);

        }










        private async Task<ApplicationUser> GetUserAsync() => await _userManager.GetUserAsync(HttpContext.User);
    }
}

Controllers/SmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using Twilio;
using Twilio.AspNet;
using Twilio.Rest.Api.V2010.Account;
using Twilio.TwiML;
using Twilio.Types;
using Twilio.AspNet.Core;
using Microsoft.Extensions.Configuration;
using DiabeticAide.Models.ViewModels;

namespace DiabeticAide.Controllers
{
    public class SmsController : TwilioController
    {


        private readonly IConfiguration Configuration;

        public SmsController(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IActionResult SendSms(string phone, string userId)
        {

            var twilioAcc = new TwilioAccount();
            Configuration.GetSection("Twilio").Bind(twilioAcc);

            var accountSid = twilioAcc.Sid;
            var authToken = twilioAcc.Token;
            TwilioClient.Init(accountSid, authToken);
            var to = new PhoneNumber($"+1{phone}");
            var from = new PhoneNumber("+12057402552");

            var message = MessageResource.Create(to: to,
                from: from,
                body: "Its time to check your blood sugar!");

            return RedirectToAction("Index", "Data");


        }
    }
}

Views/Data/Chart.cshtml
@model DiabeticAide.Models.ViewModels.UserDayChartViewModel
@using Highsoft.Web.Mvc.Charts
@using Highsoft.Web.Mvc.Charts.Rendering
@{
    ViewData["Title"] = "Index";


}



<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>



@{ var chartOptions = new Highcharts
    {
        Title = new Title
        {
            Text = Model.ChartTitle
        },
        XAxis = new List<XAxis>
        {
                    new XAxis
                    {
                        Categories = Model.ReadingTimes
                    }
                },
        Credits = new Credits
        {
            Enabled = false
        },
        Series = new List<Series>
{
                new AreaSeries
                {
                    Name = Model.Patient.FirstName,
                    Data =  Model.ReadingValues
                }

        }
    };

    chartOptions.ID = "chart";
    var renderer = new HighchartsRenderer(chartOptions);
}

@Html.Raw(renderer.RenderHtml())


@Html.ActionLink("Back to list","Details", new { userId = Model.Patient.Id })

Views/Data/Create.cshtml
@model DiabeticAide.Models.UserData

@{
    ViewData["Title"] = "Create";
    var id = ViewContext.RouteData.Values["id"];
}

<h1></h1>

<h4>UserData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="userId" value="@id"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Reading" class="control-label"></label>
                <input asp-for="Reading" class="form-control" />
                <span asp-validation-for="Reading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Data/Delete.cshtml
@model DiabeticAide.Models.UserData

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reading)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reading)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.UserId" value="@Model.UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Data/Details.cshtml
@model DiabeticAide.Models.ViewModels.UserDataViewModel

@{
    ViewData["Title"] = "Details";

}

    <h1>@Model.Patient.FirstName @Model.Patient.LastName</h1>
    <div>
        <p>
            @*<a asp-action="Create" name="userId" value="@Model.First().UserId">Create New</a>*@
            @Html.ActionLink("Create New", "Create", new { id = @Model.Patient.Id })
        </p>

        <div class="PDFandTextButtons">
            <div class="chartButtons">
            @Html.ActionLink("View Last Month's Chart", "Chart", "Data", new { patientId = Model.Patient.Id, chartLength = "Month" }, new { @class = "btn-sm btn-primary" })
            @Html.ActionLink("View Last Year's Chart", "Chart", "Data", new { patientId = Model.Patient.Id, chartLength = "Year" }, new { @class = "btn-sm btn-primary" })
            @Html.ActionLink("View Today's Chart", "Chart", "Data", new { patientId = Model.Patient.Id, chartLength = "Day" }, new { @class = "btn-sm btn-primary" })

            </div>

            @if (Model.User.Id != Model.Patient.Id)
            {
                <div class="TextButton">
                    @Html.ActionLink("Send Reminder", "SendSms", "Sms", new { phone = Model.Patient.PhoneNumber }, new { @class = "btn btn-danger" })
                </div>
            }
        </div>
    </div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UsersData.First().Reading)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsersData.First().Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UsersData.First().DateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.UsersData) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Reading)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Data/Edit.cshtml
@model DiabeticAide.Models.UserData

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <input type="hidden" name="userId" asp-for="UserId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Reading" class="control-label"></label>
                <input asp-for="Reading" class="form-control" />
                <span asp-validation-for="Reading" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="DateTime" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Data/Index.cshtml
@model IEnumerable<DiabeticAide.Models.ViewModels.UserViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Patients</h1>
<div class="cardContainer">
    @foreach (var item in Model)
    {
        <form class="userCard" asp-action="Details" asp-route-id="@item.UserId">
            <input name="userId" type="hidden" value="@item.UserId" />
            <input type="submit" value="@item.FirstName @item.LastName" class="btn-lg btn-danger" />
        </form>
    }

</div>